export default function ParcelSettings({ value, setValue, variants }: any) {
  const updateWeight = (id: string, input: string) => setValue({ ...value, variants: [...value.variants.filter((v: any) => v.id !== id), ...(Number(input) > 0 ? [{ ...value.variants.find((v: any) => v.id===id), id, packedUnitKg: Number(input) }] : [])] })
  const updateHsn = (id: string, hsn: string) => setValue({ ...value,variants:value.variants.map((v: any) => v.id===id ? {...v,hsn} : v) })
  const update = (index: number, key: string, data: any) => setValue({ ...value, parcels: value.parcels.map((p: any,i: number) => i === index ? { ...p,[key]: data } : p) })
  return <section className="ad-card"><h2>Verified packing specifications</h2><p>Measure each protected unit and the empty outer packaging separately. Approve each box only for combinations that actually fit its allowed variants and maximum units. Missing or incompatible configurations block checkout.</p>
    <details><summary>Product / hamper weights ({value.variants.length} configured)</summary><div className="launch-grid">{variants.map((v: any) => <label key={v.id}>{v.title}<input aria-label={`${v.title} protected unit weight in kilograms`} type="number" min="0.001" step="0.001" placeholder="Measured kg" value={value.variants.find((p: any) => p.id === v.id)?.packedUnitKg || ''} onChange={e => updateWeight(v.id,e.target.value)} /></label>)}</div></details>
    {!!value.variants.length && <details><summary>Product / hamper invoice classifications</summary><p>Use each verified HSN when classifications differ. Empty overrides use the verified default HSN; tax rates remain configured in Medusa.</p><div className="launch-grid">{value.variants.map((v: any) => <label key={v.id}>{variants.find((p: any) => p.id===v.id)?.title || v.id}<input aria-label={`${v.id} invoice HSN`} inputMode="numeric" maxLength={8} value={v.hsn || ''} placeholder="Verified HSN or default" onChange={e => updateHsn(v.id,e.target.value)} /></label>)}</div></details>}
    {value.parcels.map((p: any,index: number) => <fieldset className="launch-parcel" key={index}><legend>Parcel {index+1}</legend><div className="launch-grid">
      <label>Box name<input value={p.name} onChange={e => update(index,'name',e.target.value)} /></label>
      {['lengthCm','widthCm','heightCm','tareKg','maxWeightKg','maxUnits'].map(key => <label key={key}>{({ lengthCm:'Length (cm)',widthCm:'Width (cm)',heightCm:'Height (cm)',tareKg:'Empty packing weight (kg)',maxWeightKg:'Maximum packed weight (kg)',maxUnits:'Maximum protected units' } as any)[key]}<input type="number" min={key === 'tareKg' ? 0 : 0.001} step={key === 'maxUnits' ? 1 : 0.001} value={p[key] || ''} onChange={e => update(index,key,Number(e.target.value))} /></label>)}
      <label>Allowed variants<select multiple value={p.variantIds} onChange={e => update(index,'variantIds',Array.from(e.target.selectedOptions).map(o => o.value))}>{variants.map((v: any) => <option key={v.id} value={v.id}>{v.title}</option>)}</select></label>
    </div><button type="button" className="ad-btn" onClick={() => setValue({ ...value,parcels: value.parcels.filter((_: any,i: number) => i !== index) })}>Remove parcel</button></fieldset>)}
    <button type="button" className="ad-btn" onClick={() => setValue({ ...value,parcels: [...value.parcels,{ name:'',variantIds:[],maxUnits:1,tareKg:0,maxWeightKg:0,lengthCm:0,widthCm:0,heightCm:0 }] })}>Add measured parcel</button>
  </section>
}
